### ISSUE TITLE
[Technical Paper] Channel Rebalancing

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/docs#28]
- direct channels required in first phase
- check: revive rebalancing (now liquid.network)
- add lnd autopilot https://github.com/lightningnetwork/lnd/commit/306c4aef8e3af44fb3f2d8f52fc887f2c48e9c04

**Comment by sangaman** [comment]
Lnd autopilot is a configuration setting on the lnd client itself, not something that we can control externally. But being able to open an ln channel with an xud peer would be good. We'd have to exchange lightning network node keys (or maybe this is something we should store anyway about all known peers) and then call the underlying `OpenChannel` lnd method.
