### ISSUE TITLE
[Technical Paper] Attack Vectors

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/docs#33]
- Front running through public order knowledge: https://hackernoon.com/eliminating-front-running-with-decentralized-exchanges-2a5163991ffd

**Comment by sangaman** [comment]
I don't think this is an issue with layer 2 swaps. The issue as I understand it with on-chain swaps is that the swap transaction is broadcast before it is confirmed and therefore the trade becomes public knowledge before it is settled. But a swap over payment channels is private and settles nearly instantly.
