### ISSUE TITLE
Channel Management

### ISSUE THREAD

**Issue by sangaman** [ExchangeUnion/docs#42]
One topic we'll need to discuss and develop an approach for is how xud will handle payment channels.

- How much should be automated and how much should be done manually? We could also offer an optional "autopilot" mode. Some ideas that come to mind include automatically creating channels with new peers based on the trading pairs they advertise. opening new channels (or increasing channel size with splicing, or making payments in loops to rebalance) when channels become unbalanced. Mutually funded channels would be a nice feature to have for this.

- How much emphasis should we place on having direct channels with the peers we'll be trading with? Having a direct channel eliminates routing fees and improves reliability because there's no possibility of intermediary nodes going offline or failing to route payments properly. It also reduces the risk of certain attacks as well as makes attacks more easy to identify. For example, in a multi-hop payment you can't necessary tell which node is responsible for delaying or failing a payment, whereas a payment involving only two parties leaves only one person to blame. The downside of having direct payment channels with everyone is a greater capital requirement (potentially alleviated by AMP, although I'm not sure at the moment if AMP works with swaps). I think we should be prepared to support both direct and indirect/multi-hop swaps, and the latter becomes more of a necessity particularly as the network grows.

**Comment by kilrau** [comment]
https://github.com/ExchangeUnion/Docs/issues/28
