### ISSUE TITLE
xud-simnet connection is not working anymore for developers

### ISSUE THREAD

**Issue by rsercano** [ExchangeUnion/docs#53]
As explained here: https://docs.exchangeunion.com/development/developer-guide#connect-xud-to-the-xud-simnet  Previously, we were able to connect to exposed docker ports, but now this documentation is wrong because our docker images are no longer exposing the ports.

This could be fixed by changing the configuration of hosts of `lnd` and `raiden`.

**Comment by kilrau** [comment]
Good point, will add instructions to open these ports again, by adding them to the `docker-compose.yml` files.
