### ISSUE TITLE
Separate simnet, testnet, mainnet guide docs with screenshots

### ISSUE THREAD

**Issue by kilrau** [ExchangeUnion/docs#59]

**Comment by reliveyy** [comment]
Something like this? (asciinema)

[![asciicast](https://asciinema.org/a/jItnYJRndPHP5Jgj9jJ9dO5vU.svg)](https://asciinema.org/a/jItnYJRndPHP5Jgj9jJ9dO5vU)

**Comment by reliveyy** [comment]
Or using termtosvg
<details>
  <summary>Expand to view (Warning: this svg will slow down this page a lot!)</summary>
  <img src="https://raw.githubusercontent.com/reliveyy/svg-files/master/termtosvg_8x67izt7.svg?sanitize=true"/>
</details>

**Comment by kilrau** [comment]
Yeah, good idea!

**Comment by kilrau** [comment]
I'll take care of it

**Comment by reliveyy** [comment]
Third option: https://github.com/faressoft/terminalizer
This tool will record your terminal and generate animated gif images or share a web player.

**Comment by kilrau** [comment]
I went for simple bash outputs, everything else is a lot of effort to maintain since things are constantly changing. Also, I decided to not go for separate simnet/testnet/mainnet guides since all should be more or less the same on these.
