### ISSUE TITLE
Swap needed on Raspberry Pi 3?

### ISSUE THREAD

**Issue by michael1011** [ExchangeUnion/docs#88]
I tried to run xud-docker on a Raspberry Pi 3 with Neutrino and Infura but:

> One thing I noticed is that the seedutil is insanely memory hungry. I needed to setup some swap to get the environment created because the seedutil crashed because the pi ran out of ram

Could you test this on a Raspberry Pi 3 too and checkout whether you can reproduce the seedutil crashes?

**Comment by kilrau** [comment]
Was this what you saw? https://github.com/ExchangeUnion/xud/issues/1379 @michael1011

**Comment by michael1011** [comment]
Yes. It was exactly that error
